name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the version based on your project's requirement

      - name: Install dependencies and build frontend
        run: |
          cd frontend  # Change this to the folder containing your frontend code
          npm install  # Or use your package manager of choice
          npm run build  # Or the command to build your frontend assets

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: '/frontend'  # Change this to the folder containing your built frontend assets
          api_location: ''  # Leave it empty for frontend-only apps
          output_location: ''  # Leave it empty for frontend-only apps

